### ISSUE TITLE
Name passkeys

### ISSUE THREAD

**Issue by adricasti** [hidglobal/hid-passwordless#3]
Currently there is an automatically generated friendly name for a passkey, let the user set that name for easier identification

**Comment by heerahemanth1** [comment]
Added an edit button to the devices list, which enables the user to update the friendly name of the device.

![image](https://github.com/hidglobal/hid-passwordless/assets/18619407/3daa5530-5330-47cd-b2b6-239c9b7e5b6e)
![image](https://github.com/hidglobal/hid-passwordless/assets/18619407/72179fac-88e7-4b61-9faf-f58f525a29e2)
![image](https://github.com/hidglobal/hid-passwordless/assets/18619407/809a7f48-c1fc-4714-b310-1b4d60867646)
